### ISSUE TITLE
Facturación Electrónica con Odoo 10

### ISSUE THREAD

**Issue by rlguerrero888** [OCA/l10n-ecuador#21]
Buenas noches,
necesito facturación electrónica mediante el módulo PoS. Les pido por favor me puedan confirmar si es posible con este paquete creado por OCA? Si es afirmativa la respuesta, qué tipo de certificado digital debe tener la firma electrónica?
En qué parte se descarga el ATS?

**Comment by damendieta** [comment]
Saludos.

El proyecto de la OCA de localización ecuatoriana está suspendido por falta de colaboradores.

En su estado actual, el proyecto no permite la generación del ATS ni facturación electrónica.

Un abrazo.

**Comment by damendieta** [comment]
¿usted es desarrollador o desea el sistema para su empresa?

**Comment by rlguerrero888** [comment]
Estimado Daniel

Soy desarrollador y estamos moviéndonos a código abierto porque nuestros
clientes nos están solicitando Odoo.
Saludos,
Richard

**Comment by wdicado** [comment]
Hola Daniel,

Soy Ing. en sistemas, me gustaria ser parte de esta comunidad para iniciar
un trabajo serio, continuo y sostenible.

Considero que deberias reunir a quienes estemos interesados, con el único
objetivo de trabajar en una localización que tenga la gran mayoria de
necesidades empresariales.

Actualmente mi equipo y yo estamos trabajando en una localización básica
que incluye Facturas, Notas de crédito, retenciones, etc y facturación
electrónica también.

Les dejo mi teléfono.
0980972007

Cordial Saludo.

**Comment by wdicado** [comment]
Hola Daniel,

Soy Ing. en sistemas, me gustaria ser parte de esta comunidad para iniciar
un trabajo serio, continuo y sostenible.

Considero que deberias reunir a quienes estemos interesados, con el único
objetivo de trabajar en una localización que tenga la gran mayoria de
necesidades empresariales.

Actualmente mi equipo y yo estamos trabajando en una localización básica
que incluye Facturas, Notas de crédito, retenciones, etc y facturación
electrónica también.

Les dejo mi teléfono.
0980972007

Cordial Saludo.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-19 16:02 GMT-05:00 rlguerrero888 <notifications@github.com>:

> Estimado Daniel
>
> Soy desarrollador y estamos moviéndonos a código abierto porque nuestros
> clientes nos están solicitando Odoo.
> Saludos,
> Richard
>

**Comment by rlguerrero888** [comment]
Me uno a la propuesta.

Mi número es 0992601294.

**Comment by damendieta** [comment]
Si, lo he intentado varias veces, cuando empecé este repositorio hace varios años subi cerca de 20 módulos en lo que era un avance del 60% sobre la localización, luego aprendí que es necesario que los proyectos sean revisados por varias personas antes que sean unidos y que un proyecto de 10 módulos no iba a pasar por los controles de la OCA.

Retiré los módulos y los quise subir uno por uno, pero tampoco encontré quién nos ayude a revisar, ni siquiera uno por uno.

Luego hablé con todas las empresas que en ese entonces trabajaban con Odoo, ninguna quiso unirse a un proyecto colaborativo, todas querían, no solo no unirse, sino evitarlo.

Bueno, finalmente conocí a varios programadores con quienes he estado colaborando, lamentablemente una de las condiciones para trabajar en conjunto fue que el desarrollo se mantenga semi-abierto, a que me refiero con eso, a que estamos abiertos a trabajar con otras empresas pero exigimos un plan de colaboración y aportes reales.

Por ese motivo, el proyecto libre, aquí en la OCA, quedó suspendido hasta conseguir colaboración.

Si ustedes están dispuestos a colaborar, encantado de volver a trabajar desde el repositorio de la OCA.

**Comment by lojanet** [comment]
Buenas tardes, soy Ing. en informática y me gustaría contribuir con el proyecto, y sobretodo trabajar en forma coordinada, porque en la actualidad se ve que están trabajando muchos pero en forma individual, y proponiendo muchas versiones de la localización para Ecuador, lo que me parece un desperdicio de tiempo y recursos.
Mi telefono es 0986595395.

**Comment by damendieta** [comment]
Hola, te comento que estamos haciendo una localización ecuatoriana en el repositorio de software libre del Ecuador, Minka.

Puedes encontrar la información aquí.

https://minka.gob.ec/fabricadesoftwarelibre/libregob

Este proyecto busca realizar una localización completa de Ecuador, puedes encontrar más detalles aquí:

http://libregob.org/page/faq-s

Aspectos importantes son:

- Todo el código es abierto y tiene licencia AGPL-v3 (tiene compatibilidad con la OCA).
- Todos los módulos deben ser propuestos para ser integrados en Odoo y en la OCA.
- Si un módulo es aceptado en la Odoo, será retirado de la OCA para que exista en un solo lugar.
- No hay cambio de namespace, no hay módulos privados, no hay funcionalidades incompletas ni "errores" introducidos voluntariamente, 100% de compatibilidad con Odoo y los módulos de la OCA.

Si te interesa puedes hacer un fork en Minka y empezar a colaborar.

Las razones por las que no se está desarrollando directamente sobre el repositorio de la OCA o de Odoo es que queremos apoyar a la iniciativa Minka, tener mayor facilidad para hacer los merge sin necesidad de pasar por todos los controles y validaciones y que queremos llevar el proyecto en español, una vez que el módulo esté estable se realizaran las traducciónes y se propondrá la integración.

El desarrollo es público y abierto para que cualquier persona pueda colaborar.

Un abrazo.

**Comment by gomezgleonardob** [comment]
Buenos Días estoy interesado en colaborar en el desarrollo de los módulos mi cel es:0984998988

**Comment by narcisane** [comment]
Buenos dias estoy interesada en colaborar en desarrollo de modulos, no vivo en Ecuador, pero tengo experiencia en odoo

**Comment by celm1990** [comment]
Hola a todos, siguendo el hilo les comento a todos aquellos interesados que estamos trabajando en la localizacion ecuatoriana para la V15, los invito a sumarse y colaborar juntos para tenerla lo mas completa posible.
Creamos un primer PR con lo basico para emitir facturas, NC, ND y liquidacion de compras, en este PR podran encontrar mas informacion del roadmap

https://github.com/OCA/l10n-ecuador/pull/34
