### ISSUE TITLE
[12.0] definicion para implementar control de identificador

### ISSUE THREAD

**Issue by ovnicraft** [OCA/l10n-ecuador#23]
En Ecuador existe tipos de personas:
* Personas naturales 
* Personas juridicas

Cada una tiene un identificador que puede ser RUC o Cedula, esto debe ser controlado dentro del sistema.

La libreria https://arthurdejong.org/python-stdnum/formats ya tiene el control para validar estos identificadores, este issue busca definir la implementacion en Odoo v12.0

En inicio veo dos opciones para esta implementacion del modulo `l10n_ec_partner`:

1. El modulo implemente sobre `base_vat` y seguir esa arquitectura
2. El modulo tenga un diseño propio diferente a lo que hace `base_vat` 

`base_vat` https://github.com/odoo/odoo/blob/12.0/addons/base_vat/__manifest__.py

**Comment by damendieta** [comment]
Hola Cristian, actualmente estamos discutiendo la localización en un issue de Odoo directamente.

https://github.com/odoo/odoo/issues/20563

Puedes unirte y trabajar desde ahí.

También tenemos un grupo de Telegram (sé que ya eres miembro, pero lo pongo para las demás personas que quieran participar), este es el link:

https://t.me/odooec

Debido a que la OCA busca mejorar Odoo y no duplicar los módulos, creo que el orden de trabajo sería:

1.- Presentar las mejoras para que sean integradas en el core de Odoo.
2.- Las mejoras que se consideren importantes pero que sean rechazadas por Odoo se integrarían a este repositorio (de la OCA) como módulo extra.

Si tienes alguna sugerencia, de preferencia, tratemos de manejarlo directamente sobre el issue de Odoo si es en inglés y aquí si es en español.

Un abrazo.

Daniel.

**Comment by ovnicraft** [comment]
Lo he leido, ese issue es respecto al CoA, para este issue no relacionado. 
Podemos intentar ponerlo a master ya que un cambio en el modelo no lo aceptaran en la rama estable 12.0, hasta lo que mencionan en su politica https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

**Comment by damendieta** [comment]
Bueno, el issue aunque habla de un módulo es particular, se refiere a la localización en general.

Respecto de lo de proponerlo para master, es justamente eso lo que debemos hacer, como tu mencionas, los cambios importantes no van a ramas estables.

Sin embargo, el proceso sería el mismo, ver con la gente de Odoo lo que van a aceptar y lo que no acepten vendría a este repositorio.

Un abrazo.
