### ISSUE TITLE
SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by lojanet** [OCA/l10n-ecuador#43]
## Module
l10n_ec_account_edi

## Describe the bug
SyntaxError: unexpected EOF while parsing

## To Reproduce
**Affected versions**:
V15

1. Install module l10n_ec_account_edi
2. Show Full Accounting Feactures
3. In Accounting Dashboard Open any Invoice 

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by celm1990** [comment]
PR related are merged, so closing issue
