### ISSUE TITLE
[BUG] error filename / git clone on windows

### ISSUE THREAD

**Issue by rpinset** [OCA/l10n-ecuador#63]
## Module
l10n_ec_account_edi

## Describe the bug
When I git clone this repo on windows, i obtain this error :
```
error: invalid path 'l10n_ec_account_edi/tests/wsdl/AutorizacionComprobantesOffline?wsdl'
error: invalid path 'l10n_ec_account_edi/tests/wsdl/RecepcionComprobantesOffline?wsdl'
```

## To Reproduce
**Affected versions**:

1. git clone
2. git checkout 17.0
3. error

**Comment by celm1990** [comment]
fixed on https://github.com/OCA/l10n-ecuador/pull/64
